name: Deploy

on:
  release:
    types:
      - published

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    # Initialize the env variables. These get set after the repo is checked out
    # because they depend on files in the repo.
    env:
      PHP_VERSION: ''
      NODE_VERSION: ''
      THEME_VERSION: ''
      THEME_NAME: ''
      WPE_ENV: ''

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: Checkout Repo
        id: checkout_repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      # Sets the environment variables from the env.sh script.
      - name: Set Environment Variables
        id: set_env_vars
        run: .github/workflows/scripts/env.sh
      
      # Setup PHP.
      - name: Setup PHP
        id: setup_php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      # Setup Node.
      - name: Setup Node
        id: setup_node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Installs npm and composer dependencies.
      - name: Install
        id: install
        run: npm ci

      # Runs a build.
      - name: Build
        id: build
        run: npm run build

      # Extracts the built theme zip file into a .deploy/ directory.
      - name: Unzip Theme
        id: unzip_theme
        run: |
          mkdir -p .deploy
          unzip ${{ env.THEME_NAME }}.zip -d .deploy/

      # Deploys the contents of .deploy/ to the theme directory on WPEngine.
      # More information: https://my.wpengine.com/profile/github_action
      # Manage WP Engine SSH keys: https://my.wpengine.com/profile/ssh_keys
      - name: Deploy to WPEngine
        id: deploy_to_wpengine
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: ${{ env.WPE_ENV }}
          SRC_PATH: .deploy/
          REMOTE_PATH: wp-content/themes/${{ env.THEME_NAME }}/
          FLAGS: -azvr --inplace --delete
