name: Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: Checkout Repo
        id: checkout_repo
        uses: actions/checkout@v2
      
      # Gets the version from package.json and sets it as an environment variable.
      - name: Set Theme Version
        id: set_theme_version
        run: echo "THEME_VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV
        
      # Gets the Node version from .nvmrc and sets it as an environment variable.
      - name: Set Node Version
        id: set_node_version
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV
        
      # Setup Node
      - name: Setup Node
        id: setup_node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      # Installs npm and composer dependencies.
      - name: Install
        id: install
        run: npm install

      # Runs a build.
      - name: Build
        id: build
        run: npm run build
      
      # Creates a release draft.
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.THEME_VERSION }}
          tag: ${{ env.THEME_VERSION }}
          draft: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          skipIfReleaseExists: true
          artifacts: wp-theme.zip
