name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    # Initialize the env variables. These get set after the repo is checked out
    # because they depend on files in the repo.
    env:
      PHP_VERSION: ''
      NODE_VERSION: ''
      THEME_VERSION: ''
      THEME_NAME: ''

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: Checkout Repo
        id: checkout_repo
        uses: actions/checkout@v4

      # Sets the environment variables from the env.sh script.
      - name: Set Environment Variables
        id: set_env_vars
        run: .github/workflows/scripts/env.sh
      
      # Setup PHP.
      - name: Setup PHP
        id: setup_php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      # Setup Node.
      - name: Setup Node
        id: setup_node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Installs npm and composer dependencies.
      - name: Install
        id: install
        run: npm ci

      # Runs a build.
      - name: Build
        id: build
        run: npm run build

      # Creates a release draft.
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.THEME_VERSION }}
          tag: ${{ env.THEME_VERSION }}
          commit: main
          draft: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          skipIfReleaseExists: true
          artifacts: ${{ env.THEME_NAME }}.zip
