name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    # Initialize the env variables. These get set after the repo is checked out
    # because they depend on files in the repo.
    env:
      PACKAGE_VERSION: ''

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: Checkout Repo
        id: checkout_repo
        uses: actions/checkout@v4

      # Sets the environment variables from the env.sh script.
      - name: Set Environment Variables
        id: set_env_vars
        run: .github/workflows/scripts/env.sh

      # Creates a release draft.
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.PACKAGE_VERSION }}
          tag: ${{ env.PACKAGE_VERSION }}
          commit: master
          draft: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          skipIfReleaseExists: true
