name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    # Initialize the env variables. These get set after the repo is checked out
    # because they depend on files in the repo.
    env:
      PHP_VERSION: ''
      NODE_VERSION: ''
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: Checkout Repo
        id: checkout_repo
        uses: actions/checkout@v4

      # Sets the environment variables from the env.sh script.
      - name: Set Environment Variables
        id: set_env_vars
        working-directory: package
        run: .github/workflows/scripts/env.sh
      
      # Setup PHP.
      - name: Setup PHP
        id: setup_php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      # Setup Node.
      - name: Setup Node
        id: setup_node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Installs npm and composer dependencies. Note that we use `npm install`
      # instead of `npm ci` because we do not yet have a lock file.
      - name: Install
        id: install
        working-directory: package
        run: npm install
      
      # Lint all files.
      - name: Lint
        id: lint
        working-directory: package
        run: npm run lint

      # Runs a build.
      - name: Build
        id: build
        working-directory: package
        run: npm run build
